
"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['style.qss', 'logo.png']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['cv2', 'numpy', 'PyQt5'],
    'iconfile': 'app.icns', # Assuming you might want an icon later
    'plist': {
        'CFBundleName': 'ProjectionMapper',
        'CFBundleDisplayName': 'Projection Mapper',
        'CFBundleGetInfoString': "Real-time projection mapping tool",
        'CFBundleIdentifier': "com.yourcompany.projectionmapper",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, Your Company, Inc. All Rights Reserved"
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
